#######################################################################
# Configs
#######################################################################
$configs = {
	# HTML reporting only: If an HTML report is being generated, this
	# information will be printed into the report.
	:client_name		=> "Enzo's Pizza",

	# HTML reporting only: if set to true, all JavaScript dependencies
	# will be embedded directly into the report file. If set to false,
	# they will be linked to a hosted CDN from within the generated 
	# report.
	#
	# Embedding JavaScript directly in the report makes it possible
	# to use all of the functionality of the HTML report even when
	# no Internet connection is available, but will increase the
	# file size of the report.
	:embed_javascript 	=> true,
	
	# You may exclude directories from the scan
	:exclude_dirs		=> [
		#'/path/to/ignore/one',
		#'/path/to/ignore/two',
	],
	
	# HTML reporting only: This text will be displayed in the report's
	# footer area
	:footer_text 		=> "Report generated by <a href='https://github.com/chrisallenlane/watchtower'>Watchtower</a>.",
	
	# HTML reporting only: This text will be displayed in the report's
	# header area
	:header_text 		=> "
	<div id='masthead_right'>
		<h4>Auditor:</h4>
		<p>Hiro Protagonist
		<br><a href='#'>hiro@example.com</a>
		<br><a href='#'>blog.example.com</a>
		<br><a href='#'>twitter.com/example</a></p>
	</div>
	",
	
	# HTML reporting only: the path to the ERB template to use
	# for generating the HTML report.
	:report_file		=> './lib/reports/report.html.erb',
	
	# HTML reporting only: the stylesheets to embed into the outputted
	# report.
	:stylesheets 		=> [
		'./lib/static/jquery-ui-1.8.19.custom.css',
		'./lib/static/main.css',
	],
	
	# The paths to the files containing the signatures for which you
	# would like to scan.
	:signatures 			=> [
		# './signatures/c.rb',
		'./signatures/html.rb',
		'./signatures/php.rb',
		'./signatures/js.rb',
		# './signatures/sql.rb',
		# './signatures/wordpress.rb',
	].sort,
}


#######################################################################
# Signatures
#######################################################################
# assemble the array of signatures
$signatures ||= {}
$configs[:signatures].each {|signature| require signature}
