#!/usr/bin/env ruby
#######################################################################
# Watchtower - a Static Code Analysis tool for security auditors
#
# Chris Lane
# chris@chris-allen-lane.com
# http://chris-allen-lane.com
# http://twitter.com/chrisallenlane
#######################################################################

require 'rubygems'
require 'digest'
require 'fileutils'
require 'trollop'
require 'lib/models/poi'
require 'lib/models/signature'
require 'lib/models/vulnscanner'


#######################################################################
# Menu options and program flow
#######################################################################
opts = Trollop::options do
	banner File.read('./lib/static/banner.txt')
	
	version 'Version: 1.3.1'

	opt :scan_dir,		'The directory to scan',
			:type 		=> :string,
			:required	=> true,
			:short 		=> 's'

	opt :colorize,		'Colorizes command-line output',
			:short 		=> 'c'

	opt :config_file,	'Path to the config file.',
			:type 		=> :string,
			:default	=> './config.rb',
			:short 		=> 'f'

	opt :output_format,	'Specify the output format. Valid options are "csv", ' + 
			'"html", "markdown", "txt", and "xml"',
			:default	=> 'txt',
			:short 		=> 'o'
			
	opt :project_name, 'The name of the project (useful when outputting an HTML report)',
			:type 		=> :string,
			:short 		=> 'p'
			
	opt :before_context, 'print NUM lines of leading context',
			:type 		=> :int,
			:required	=> false,
			:default	=> 1,
			:short		=> 'B'

	opt :after_context, 'print NUM lines of trailing context',
			:type 		=> :int,
			:required	=> false,
			:default	=> 1,
			:short		=> 'A'

	opt :context, 'print NUM lines of output context',
			:type 		=> :int,
			:required	=> false,
			:default	=> 3,
			:short		=> 'C'
end
	

#######################################################################
# Configs, Signatures, and Option Validation
#######################################################################
# Load the configuration file
unless File.exists? opts[:config_file]
	warn 'The specified config file does not exist.'
	exit
end
require opts[:config_file]

# Verify that the directory to scan actually exists
unless File.exists? opts[:scan_dir]
	warn 'The specified directory to scan does not exist.'
	exit
end

# Verify that -A and -B are >= 1
if (opts[:before_context] < 1) or (opts[:after_context] < 1)
    warn 'Options --before-context and --after-context may not be less than 1.'
    exit
end

# Verify that -C is >= 3
if opts[:context] < 3
    warn 'Option --context may not be less than 3.'
    exit
end


#######################################################################
# Scan
#######################################################################
vulnscanner = VulnScanner.new({
	:signatures		=> $signatures,
	:scan_dir		=> opts[:scan_dir],
	:before_context	=> opts[:before_context],
	:after_context	=> opts[:after_context],
	:context    	=> (opts[:context_given]) ? opts[:context] : false,
})
vulnscanner.scan


#######################################################################
# Display
#######################################################################
# output in the requested format
case opts[:output_format]
	when 'csv'
		require 'fastercsv'
		# kludge in a header row
		puts '"file_type","file","line_number","match","name","snippet","group"'
		csv_string = FasterCSV.generate(:force_quotes => true) do |csv|
			vulnscanner.points_of_interest.each {|point| csv << point.to_a}
		end
		puts csv_string
		
	when 'html'
		# require erb for templating
		require 'erb'
		include ERB::Util
		
		# sort the points of interest for HTML output
		vulnscanner.sort
		
		# parse and display the HTML output
		erb = ERB.new(File.read($configs[:report_file_html]), 0, '<>', 'buffer')
		puts erb.result(binding)
		
	when 'markdown'
		# require erb for templating
		require 'erb'
		include ERB::Util
		
		# sort the points of interest for HTML output
		vulnscanner.sort
		
		# parse and display the HTML output
		erb = ERB.new(File.read($configs[:report_file_markdown]), 0, '<>', 'buffer')
		puts erb.result(binding)
	
	when 'xml'
		puts '<points_of_interest>'
		vulnscanner.points_of_interest.each {|point| puts point.to_xml}
		puts '</points_of_interest>'
	
	else
		if opts[:colorize_given]
			require 'colorize'
			vulnscanner.points_of_interest.each {|point| point.colorize; puts point + "\n\n"}
		else
			vulnscanner.points_of_interest.each {|point| puts point + "\n\n"}
		end
end
